Updating the return codes in the `harper_deb13_kernel_trigger` function to better differentiate between an error and a situation where no build is needed. Additionally, updating the workflow to handle the new return code appropriately.

diff --git a/.forgejo/workflows/monitor-deb13-kernel.yml b/.forgejo/workflows/monitor-deb13-kernel.yml
--- a/.forgejo/workflows/monitor-deb13-kernel.yml
+++ b/.forgejo/workflows/monitor-deb13-kernel.yml
@@ -67,9 +67,12 @@ jobs:
             echo "build_needed=true" >> $GITHUB_OUTPUT           
             echo "🚀 New kernel found. Waking $YML__FORGEJO_RUNNER_BUILDER..."
             /scripts/alice_power.sh on
-          else
+          elif [[ "$build_return_code" -eq 2 ]]; then
             echo "build_needed=false" >> $GITHUB_OUTPUT
             echo "ℹ️ No update needed."
+          else
+            echo "❌ Error checking for kernel update. See logs for details."
+            exit 1 
           fi
   
   compile-on-builder:
